package org.fin.definitions.assets;

import lombok.Getter;
import org.series.ZoneIdEnum;

@Getter
public enum Stock implements Purchasable{
    AC("AC.PA", "Accor", Field.HOTELS_RESTAURANTS_LEISURE, Country.FR, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    AI("AI.PA", "Air Liquide", Field.CHEMICALS, Country.FR, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    AIR("AIR.PA", "Airbus", Field.AEROSPACE_DEFENSE, Country.FR, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
//    MT("MT.PA", "ArcelorMittal", Field.METALS_MINING, Country.FR, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    CS("CS.PA", "AXA", Field.INSURANCE, Country.FR, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    BNP("BNP.PA", "BNP Paribas", Field.BANKS, Country.FR, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    EN("EN.PA", "Bouygues", Field.CONSTRUCTION_ENGINEERING, Country.FR, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    CAP("CAP.PA", "Capgemini", Field.IT_SERVICES, Country.FR, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    CA("CA.PA", "Carrefour", Field.FOOD_STAPLES_RETAILING, Country.FR, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    ACA("ACA.PA", "Crédit Agricole", Field.BANKS, Country.FR, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    BN("BN.PA", "Danone", Field.FOOD_PRODUCTS, Country.FR, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    DSY("DSY.PA", "Dassault Systèmes", Field.SOFTWARE, Country.FR, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    EDEN("EDEN.PA", "Edenred", Field.PROFESSIONAL_SERVICES, Country.FR, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    ENGI("ENGI.PA", "Engie", Field.MULTI_UTILITIES, Country.FR, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    EL("EL.PA", "EssilorLuxottica", Field.HEALTHCARE_EQUIPMENT_SUPPLIES, Country.FR, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    ERF("ERF.PA", "Eurofins Scientific", Field.LIFE_SCIENCES_TOOLS_SERVICES, Country.FR, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    RMS("RMS.PA", "Hermès International", Field.TEXTILES_APPAREL_LUXURY_GOODS, Country.FR, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    KER("KER.PA", "Kering", Field.TEXTILES_APPAREL_LUXURY_GOODS, Country.FR, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    OR("OR.PA", "L'Oréal", Field.PERSONAL_PRODUCTS, Country.FR, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    LR("LR.PA", "Legrand", Field.ELECTRICAL_EQUIPMENT, Country.FR, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    MC("MC.PA", "LVMH", Field.TEXTILES_APPAREL_LUXURY_GOODS, Country.FR, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    ML("ML.PA", "Michelin", Field.AUTO_COMPONENTS, Country.FR, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    ORA("ORA.PA", "Orange", Field.DIVERSIFIED_TELECOMMUNICATION_SERVICES, Country.FR, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    RI("RI.PA", "Pernod Ricard", Field.BEVERAGES, Country.FR, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    PUB("PUB.PA", "Publicis Groupe", Field.MEDIA, Country.FR, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    RNO("RNO.PA", "Renault", Field.AUTOMOBILES, Country.FR, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    SAF("SAF.PA", "Safran", Field.AEROSPACE_DEFENSE, Country.FR, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    SGO("SGO.PA", "Saint-Gobain", Field.BUILDING_PRODUCTS, Country.FR, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    SAN("SAN.PA", "Sanofi", Field.PHARMACEUTICALS, Country.FR, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    SU("SU.PA", "Schneider Electric", Field.ELECTRICAL_EQUIPMENT, Country.FR, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    GLE("GLE.PA", "Société Générale", Field.BANKS, Country.FR, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    STLAP("STLAP.PA", "Stellantis", Field.AUTOMOBILES, Country.FR, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    STMPA("STMPA.PA", "STMicroelectronics", Field.SEMICONDUCTORS, Country.FR, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    TEP("TEP.PA", "Teleperformance", Field.PROFESSIONAL_SERVICES, Country.FR, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    HO("HO.PA", "Thales", Field.AEROSPACE_DEFENSE, Country.FR, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    TTE("TTE.PA", "TotalEnergies", Field.OIL_GAS_CONSUMABLE_FUELS, Country.FR, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    URW("URW.PA", "Unibail-Rodamco-Westfield", Field.EQUITY_REAL_ESTATE_INVESTMENT_TRUSTS, Country.FR, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    VIE("VIE.PA", "Veolia Environnement", Field.MULTI_UTILITIES, Country.FR, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    DG("DG.PA", "Vinci", Field.CONSTRUCTION_ENGINEERING, Country.FR, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    VIV("VIV.PA", "Vivendi", Field.MEDIA, Country.FR, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),

    // --- CAC NEXT 20 ---
    ALO("ALO.PA", "Alstom", Field.MACHINERY, Country.FR, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
//    RKE("RKE.PA", "Arkema", Field.CHEMICALS, Country.FR, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    BIM("BIM.PA", "BioMérieux", Field.HEALTHCARE_EQUIPMENT_SUPPLIES, Country.FR, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    BVI("BVI.PA", "Bureau Veritas", Field.PROFESSIONAL_SERVICES, Country.FR, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    AM("AM.PA", "Dassault Aviation", Field.AEROSPACE_DEFENSE, Country.FR, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    FGG("FGR.PA", "Eiffage", Field.CONSTRUCTION_ENGINEERING, Country.FR, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    GFC("GFC.PA", "Gecina", Field.EQUITY_REAL_ESTATE_INVESTMENT_TRUSTS, Country.FR, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    GET("GET.PA", "Getlink", Field.TRANSPORTATION_INFRASTRUCTURE, Country.FR, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    IPN("IPN.PA", "Ipsen", Field.PHARMACEUTICALS, Country.FR, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    LI("LI.PA", "Klépierre", Field.EQUITY_REAL_ESTATE_INVESTMENT_TRUSTS, Country.FR, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    RXL("RXL.PA", "Rexel", Field.TRADING_DISTRIBUTORS, Country.FR, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    DIM("DIM.PA", "Sartorius Stedim Biotech", Field.LIFE_SCIENCES_TOOLS_SERVICES, Country.FR, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    SCR("SCR.PA", "SCOR", Field.INSURANCE, Country.FR, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    SW("SW.PA", "Sodexo", Field.HOTELS_RESTAURANTS_LEISURE, Country.FR, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    SOI("SOI.PA", "Soitec", Field.SEMICONDUCTORS, Country.FR, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    SOLB("SOL0.F", "Solvay", Field.CHEMICALS, Country.FR, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    SPIE("SPIE.PA", "SPIE", Field.CONSTRUCTION_ENGINEERING, Country.FR, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    TE("TE.PA", "Technip Energies", Field.CONSTRUCTION_ENGINEERING, Country.FR, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    UBI("UBI.PA", "Ubisoft Entertainment", Field.ENTERTAINMENT, Country.FR, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    WLN("WLN.PA", "Worldline", Field.IT_SERVICES, Country.FR, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),

    // --- CAC MID 60 ---
    AF("AF.PA", "Air France-KLM", Field.AIRLINES, Country.FR, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    ATE("ATE.PA", "Alten", Field.IT_SERVICES, Country.FR, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    AMUN("AMUN.PA", "Amundi", Field.CAPITAL_MARKETS, Country.FR, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    APAM("7AA.HM", "Aperam", Field.METALS_MINING, Country.FR, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    ARG("ARG.PA", "Argan", Field.EQUITY_REAL_ESTATE_INVESTMENT_TRUSTS, Country.FR, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    BEN("BEN.PA", "Beneteau", Field.LEISURE_PRODUCTS, Country.FR, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    BB("BB.PA", "Bic", Field.HOUSEHOLD_PRODUCTS, Country.FR, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    BOL("BOL.PA", "Bolloré", Field.INDUSTRIAL_CONGLOMERATES, Country.FR, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    CARM("CARM.PA", "Carmila", Field.EQUITY_REAL_ESTATE_INVESTMENT_TRUSTS, Country.FR, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    CLARI("CLARI.PA", "Clariane", Field.HEALTHCARE_PROVIDERS_SERVICES, Country.FR, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    COFA("COFA.PA", "Coface", Field.INSURANCE, Country.FR, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    COV("COV.PA", "Covivio", Field.EQUITY_REAL_ESTATE_INVESTMENT_TRUSTS, Country.FR, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    DBG("DBG.PA", "Derichebourg", Field.PROFESSIONAL_SERVICES, Country.FR, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    ELIOR("ELIOR.PA", "Elior Group", Field.HOTELS_RESTAURANTS_LEISURE, Country.FR, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    ELIS("ELIS.PA", "Elis", Field.PROFESSIONAL_SERVICES, Country.FR, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    RF("RF.PA", "Eurazeo", Field.CAPITAL_MARKETS, Country.FR, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    EAPI("EAPI.PA", "Euroapi", Field.PHARMACEUTICALS, Country.FR, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    ETL("ETL.PA", "Eutelsat Communications", Field.DIVERSIFIED_TELECOMMUNICATION_SERVICES, Country.FR, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    FNAC("FNAC.PA", "Fnac Darty", Field.SPECIALTY_RETAIL, Country.FR, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    FRVIA("FRVIA.PA", "Forvia", Field.AUTO_COMPONENTS, Country.FR, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    GTT("GTT.PA", "Gaztransport et Technigaz", Field.ENERGY_EQUIPMENT_SERVICES, Country.FR, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    ICAD("ICAD.PA", "Icade", Field.EQUITY_REAL_ESTATE_INVESTMENT_TRUSTS, Country.FR, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    IDL("IDL.PA", "ID Logistics", Field.AIR_FREIGHT_LOGISTICS, Country.FR, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    NK("NK.PA", "Imerys", Field.CONSTRUCTION_MATERIALS, Country.FR, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    ITP("ITP.PA", "Interparfums", Field.PERSONAL_PRODUCTS, Country.FR, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    IPS("IPS.PA", "Ipsos", Field.MEDIA, Country.FR, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    DEC("DEC.PA", "JCDecaux", Field.MEDIA, Country.FR, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    FII("FII.PA", "LISI", Field.BUILDING_PRODUCTS, Country.FR, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    MDM("MDM.PA", "Maisons du Monde", Field.SPECIALTY_RETAIL, Country.FR, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    MERY("MERY.PA", "Mercialys", Field.EQUITY_REAL_ESTATE_INVESTMENT_TRUSTS, Country.FR, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    MMT("MMT.PA", "Métropole TV", Field.MEDIA, Country.FR, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    NEX("NEX.PA", "Nexans", Field.ELECTRICAL_EQUIPMENT, Country.FR, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    NXI("NXI.PA", "Nexity", Field.REAL_ESTATE_MANAGEMENT_DEVELOPMENT, Country.FR, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    OPM("OPM.PA", "OPmobility", Field.AUTO_COMPONENTS, Country.FR, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    PEUG("PEUG.PA", "Peugeot Invest", Field.DIVERSIFIED_FINANCIAL_SERVICES, Country.FR, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    RBT("RBT.PA", "Robertet", Field.CHEMICALS, Country.FR, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    RUI("RUI.PA", "Rubis", Field.OIL_GAS_CONSUMABLE_FUELS, Country.FR, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    SK("SK.PA", "SEB", Field.HOUSEHOLD_DURABLES, Country.FR, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    SMCP("SMCP.PA", "SMCP", Field.TEXTILES_APPAREL_LUXURY_GOODS, Country.FR, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    S30("S30.PA", "Solutions 30", Field.IT_SERVICES, Country.FR, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    SOP("SOP.PA", "Sopra Steria Group", Field.IT_SERVICES, Country.FR, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    SDG("SDG.PA", "Synergie", Field.PROFESSIONAL_SERVICES, Country.FR, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    TFI("TFI.PA", "TF1", Field.MEDIA, Country.FR, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    TKO("TKO.PA", "Tikehau Capital", Field.CAPITAL_MARKETS, Country.FR, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    TRI("TRI.PA", "Trigano", Field.AUTOMOBILES, Country.FR, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    VK("VK.PA", "Vallourec", Field.ENERGY_EQUIPMENT_SERVICES, Country.FR, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    VLA("VLA.PA", "Valneva", Field.BIOTECHNOLOGY, Country.FR, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    VANTI("VANTI.PA", "Vantiva", Field.TECHNOLOGY_HARDWARE_STORAGE_PERIPHERALS, Country.FR, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    VRLA("VRLA.PA", "Verallia", Field.CONTAINERS_PACKAGING, Country.FR, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    VCT("VCT.PA", "Vicat", Field.CONSTRUCTION_MATERIALS, Country.FR, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    VIRP("VIRP.PA", "Virbac", Field.PHARMACEUTICALS, Country.FR, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    VLTSA("VLTSA.PA", "Voltalia", Field.INDEPENDENT_POWER_PRODUCERS_ENERGY_TRADERS, Country.FR, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    VU("VU.PA", "VusionGroup", Field.ELECTRONIC_EQUIPMENT_INSTRUMENTS_COMPONENTS, Country.FR, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    WAVE("WAVE.PA", "Wavestone", Field.IT_SERVICES, Country.FR, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    REND("MF.PA", "Wendel", Field.CAPITAL_MARKETS, Country.FR, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    XFAB("XFAB.PA", "X-Fab", Field.SEMICONDUCTORS, Country.FR, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),

    ADS("ADS.DE", "Adidas", Field.TEXTILES_APPAREL_LUXURY_GOODS, Country.DE, Currency.EUR, ZoneIdEnum.EUROPE_ZURICH),
    AIR_DE("AIR.DE", "Airbus", Field.AEROSPACE_DEFENSE, Country.DE, Currency.EUR, ZoneIdEnum.EUROPE_ZURICH),
    ALV("ALV.DE", "Allianz", Field.INSURANCE, Country.DE, Currency.EUR, ZoneIdEnum.EUROPE_ZURICH),
    BAS("BAS.DE", "BASF", Field.CHEMICALS, Country.DE, Currency.EUR, ZoneIdEnum.EUROPE_ZURICH),
    BAYN("BAYN.DE", "Bayer", Field.PHARMACEUTICALS, Country.DE, Currency.EUR, ZoneIdEnum.EUROPE_ZURICH),
    BEI("BEI.DE", "Beiersdorf", Field.PERSONAL_PRODUCTS, Country.DE, Currency.EUR, ZoneIdEnum.EUROPE_ZURICH),
    BMW("BMW.DE", "BMW", Field.AUTOMOBILES, Country.DE, Currency.EUR, ZoneIdEnum.EUROPE_ZURICH),
    BNR("BNR.DE", "Brenntag", Field.TRADING_DISTRIBUTORS, Country.DE, Currency.EUR, ZoneIdEnum.EUROPE_ZURICH),
    CBK("CBK.DE", "Commerzbank", Field.BANKS, Country.DE, Currency.EUR, ZoneIdEnum.EUROPE_ZURICH),
    CON("CON.DE", "Continental", Field.AUTO_COMPONENTS, Country.DE, Currency.EUR, ZoneIdEnum.EUROPE_ZURICH),
    DTG("DTG.DE", "Daimler Truck", Field.MACHINERY, Country.DE, Currency.EUR, ZoneIdEnum.EUROPE_ZURICH),
    DB1("DB1.DE", "Deutsche Börse", Field.CAPITAL_MARKETS, Country.DE, Currency.EUR, ZoneIdEnum.EUROPE_ZURICH),
    DBK("DBK.DE", "Deutsche Bank", Field.BANKS, Country.DE, Currency.EUR, ZoneIdEnum.EUROPE_ZURICH),
    DHL("DHL.DE", "DHL Group", Field.AIR_FREIGHT_LOGISTICS, Country.DE, Currency.EUR, ZoneIdEnum.EUROPE_ZURICH),
    DTE("DTE.DE", "Deutsche Telekom", Field.DIVERSIFIED_TELECOMMUNICATION_SERVICES, Country.DE, Currency.EUR, ZoneIdEnum.EUROPE_ZURICH),
    EOAN("EOAN.DE", "E.ON", Field.MULTI_UTILITIES, Country.DE, Currency.EUR, ZoneIdEnum.EUROPE_ZURICH),
    FRE("FRE.DE", "Fresenius", Field.HEALTHCARE_PROVIDERS_SERVICES, Country.DE, Currency.EUR, ZoneIdEnum.EUROPE_ZURICH),
    HEI("HEI.DE", "Heidelberg Materials", Field.CONSTRUCTION_MATERIALS, Country.DE, Currency.EUR, ZoneIdEnum.EUROPE_ZURICH),
    HEN3("HEN3.DE", "Henkel", Field.HOUSEHOLD_PRODUCTS, Country.DE, Currency.EUR, ZoneIdEnum.EUROPE_ZURICH),
    HNR1("HNR1.DE", "Hannover Rück", Field.INSURANCE, Country.DE, Currency.EUR, ZoneIdEnum.EUROPE_ZURICH),
    IFX("IFX.DE", "Infineon Technologies", Field.SEMICONDUCTORS, Country.DE, Currency.EUR, ZoneIdEnum.EUROPE_ZURICH),
    MBG("MBG.DE", "Mercedes-Benz Group", Field.AUTOMOBILES, Country.DE, Currency.EUR, ZoneIdEnum.EUROPE_ZURICH),
    MRK("MRK.DE", "Merck KGaA", Field.PHARMACEUTICALS, Country.DE, Currency.EUR, ZoneIdEnum.EUROPE_ZURICH),
    MTX("MTX.DE", "MTU Aero Engines", Field.AEROSPACE_DEFENSE, Country.DE, Currency.EUR, ZoneIdEnum.EUROPE_ZURICH),
    MUV2("MUV2.DE", "Münchener Rück", Field.INSURANCE, Country.DE, Currency.EUR, ZoneIdEnum.EUROPE_ZURICH),
    P911("P911.DE", "Porsche AG", Field.AUTOMOBILES, Country.DE, Currency.EUR, ZoneIdEnum.EUROPE_ZURICH),
    PAH3("PAH3.DE", "Porsche SE", Field.AUTOMOBILES, Country.DE, Currency.EUR, ZoneIdEnum.EUROPE_ZURICH),
    QIA("QIA.DE", "Qiagen", Field.LIFE_SCIENCES_TOOLS_SERVICES, Country.DE, Currency.EUR, ZoneIdEnum.EUROPE_ZURICH),
    RWE("RWE.DE", "RWE", Field.MULTI_UTILITIES, Country.DE, Currency.EUR, ZoneIdEnum.EUROPE_ZURICH),
    RHM("RHM.DE", "Rheinmetall", Field.AEROSPACE_DEFENSE, Country.DE, Currency.EUR, ZoneIdEnum.EUROPE_ZURICH),
    SAP("SAP.DE", "SAP", Field.SOFTWARE, Country.DE, Currency.EUR, ZoneIdEnum.EUROPE_ZURICH),
    SRT3("SRT3.DE", "Sartorius", Field.LIFE_SCIENCES_TOOLS_SERVICES, Country.DE, Currency.EUR, ZoneIdEnum.EUROPE_ZURICH),
    SIE("SIE.DE", "Siemens", Field.INDUSTRIAL_CONGLOMERATES, Country.DE, Currency.EUR, ZoneIdEnum.EUROPE_ZURICH),
    SHL("SHL.DE", "Siemens Healthineers", Field.HEALTHCARE_EQUIPMENT_SUPPLIES, Country.DE, Currency.EUR, ZoneIdEnum.EUROPE_ZURICH),
    ENR("ENR.DE", "Siemens Energy", Field.ELECTRICAL_EQUIPMENT, Country.DE, Currency.EUR, ZoneIdEnum.EUROPE_ZURICH),
    SY1("SY1.DE", "Symrise", Field.CHEMICALS, Country.DE, Currency.EUR, ZoneIdEnum.EUROPE_ZURICH),
    VOW3("VOW3.DE", "Volkswagen", Field.AUTOMOBILES, Country.DE, Currency.EUR, ZoneIdEnum.EUROPE_ZURICH),
    VNA("VNA.DE", "Vonovia", Field.REAL_ESTATE_MANAGEMENT_DEVELOPMENT, Country.DE, Currency.EUR, ZoneIdEnum.EUROPE_ZURICH),
    ZAL("ZAL.DE", "Zalando", Field.INTERNET_DIRECT_MARKETING_RETAIL, Country.DE, Currency.EUR, ZoneIdEnum.EUROPE_ZURICH),

    ABBN("ABBN.SW", "ABB", Field.ELECTRICAL_EQUIPMENT, Country.CH, Currency.CHF, ZoneIdEnum.EUROPE_ZURICH),
    CFR("CFR.SW", "Richemont", Field.TEXTILES_APPAREL_LUXURY_GOODS, Country.CH, Currency.CHF, ZoneIdEnum.EUROPE_ZURICH),
    GEBN("GEBN.SW", "Geberit", Field.BUILDING_PRODUCTS, Country.CH, Currency.CHF, ZoneIdEnum.EUROPE_ZURICH),
    GIVN("GIVN.SW", "Givaudan", Field.CHEMICALS, Country.CH, Currency.CHF, ZoneIdEnum.EUROPE_ZURICH),
    HOLN("HOLN.SW", "Holcim", Field.CONSTRUCTION_MATERIALS, Country.CH, Currency.CHF, ZoneIdEnum.EUROPE_ZURICH),
    LOGN("LOGN.SW", "Logitech", Field.TECHNOLOGY_HARDWARE_STORAGE_PERIPHERALS, Country.CH, Currency.CHF, ZoneIdEnum.EUROPE_ZURICH),
    LONN("LONN.SW", "Lonza Group", Field.LIFE_SCIENCES_TOOLS_SERVICES, Country.CH, Currency.CHF, ZoneIdEnum.EUROPE_ZURICH),
    NESN("NESN.SW", "Nestlé", Field.FOOD_PRODUCTS, Country.CH, Currency.CHF, ZoneIdEnum.EUROPE_ZURICH),
    NOVN("NOVN.SW", "Novartis", Field.PHARMACEUTICALS, Country.CH, Currency.CHF, ZoneIdEnum.EUROPE_ZURICH),
    PGHN("PGHN.SW", "Partners Group", Field.CAPITAL_MARKETS, Country.CH, Currency.CHF, ZoneIdEnum.EUROPE_ZURICH),
    ROG("ROP.SW", "Roche", Field.PHARMACEUTICALS, Country.CH, Currency.CHF, ZoneIdEnum.EUROPE_ZURICH),
    SCMN("SCMN.SW", "Swisscom", Field.DIVERSIFIED_TELECOMMUNICATION_SERVICES, Country.CH, Currency.CHF, ZoneIdEnum.EUROPE_ZURICH),
    SIKA("SIKA.SW", "Sika", Field.CHEMICALS, Country.CH, Currency.CHF, ZoneIdEnum.EUROPE_ZURICH),
    SLHN("SLHN.SW", "Swiss Life", Field.INSURANCE, Country.CH, Currency.CHF, ZoneIdEnum.EUROPE_ZURICH),
    SREN("SREN.SW", "Swiss Re", Field.INSURANCE, Country.CH, Currency.CHF, ZoneIdEnum.EUROPE_ZURICH),
    STMN("STMN.SW", "Straumann", Field.HEALTHCARE_EQUIPMENT_SUPPLIES, Country.CH, Currency.CHF, ZoneIdEnum.EUROPE_ZURICH),
    UBSG("UBSG.SW", "UBS Group", Field.BANKS, Country.CH, Currency.CHF, ZoneIdEnum.EUROPE_ZURICH),
    VATN("VATN.SW", "VAT Group", Field.MACHINERY, Country.CH, Currency.CHF, ZoneIdEnum.EUROPE_ZURICH),
    ZURN("ZURN.SW", "Zurich Insurance", Field.INSURANCE, Country.CH, Currency.CHF, ZoneIdEnum.EUROPE_ZURICH),

    A2A("A2A.MI", "A2A", Field.MULTI_UTILITIES, Country.IT, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    AMP("AMP.MI", "Amplifon", Field.HEALTHCARE_EQUIPMENT_SUPPLIES, Country.IT, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    SRG("SRG.MI", "Snam", Field.GAS_UTILITIES, Country.IT, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    BPE("BPE.MI", "BPER Banca", Field.BANKS, Country.IT, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    BAMI("BAMI.MI", "Banco BPM", Field.BANKS, Country.IT, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    BMED("BMED.MI", "Banca Mediolanum", Field.BANKS, Country.IT, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    CPR("CPR.MI", "Campari", Field.BEVERAGES, Country.IT, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    DIA("DIA.MI", "Diasorin", Field.HEALTHCARE_EQUIPMENT_SUPPLIES, Country.IT, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    ENEL("ENEL.MI", "Enel", Field.ELECTRIC_UTILITIES, Country.IT, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    ENI("ENI.MI", "Eni", Field.OIL_GAS_CONSUMABLE_FUELS, Country.IT, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    ERG("ERG.MI", "ERG", Field.INDEPENDENT_POWER_PRODUCERS_ENERGY_TRADERS, Country.IT, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    RACE("RACE.MI", "Ferrari", Field.AUTOMOBILES, Country.IT, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    FBK("FBK.MI", "FinecoBank", Field.BANKS, Country.IT, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    G("G.MI", "Generali", Field.INSURANCE, Country.IT, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    HER("HER.MI", "Hera", Field.MULTI_UTILITIES, Country.IT, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    IP("IP.MI", "Interpump Group", Field.MACHINERY, Country.IT, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    ISP("ISP.MI", "Intesa Sanpaolo", Field.BANKS, Country.IT, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    INW("INW.MI", "Inwit", Field.DIVERSIFIED_TELECOMMUNICATION_SERVICES, Country.IT, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    IG("IG.MI", "Italgas", Field.GAS_UTILITIES, Country.IT, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    IVE("IVG.MI", "Iveco Group", Field.MACHINERY, Country.IT, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    LDO("LDO.MI", "Leonardo", Field.AEROSPACE_DEFENSE, Country.IT, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    MB("MB.MI", "Mediobanca", Field.BANKS, Country.IT, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    MONC("MONC.MI", "Moncler", Field.TEXTILES_APPAREL_LUXURY_GOODS, Country.IT, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    NEXI("NEXI.MI", "Nexi", Field.IT_SERVICES, Country.IT, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    PIR("PIRC.MI", "Pirelli", Field.AUTO_COMPONENTS, Country.IT, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    PST("PST.MI", "Poste Italiane", Field.DIVERSIFIED_FINANCIAL_SERVICES, Country.IT, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    PRY("PRY.MI", "Prysmian", Field.ELECTRICAL_EQUIPMENT, Country.IT, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    REC("REC.MI", "Recordati", Field.PHARMACEUTICALS, Country.IT, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    SPM("SPM.MI", "Saipem", Field.ENERGY_EQUIPMENT_SERVICES, Country.IT, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    STLAM("STLAM.MI", "Stellantis", Field.AUTOMOBILES, Country.IT, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    STMMI("STMMI.MI", "STMicroelectronics", Field.SEMICONDUCTORS, Country.IT, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    TIT("TIT.MI", "Telecom Italia", Field.DIVERSIFIED_TELECOMMUNICATION_SERVICES, Country.IT, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    TEN("TEN.MI", "Tenaris", Field.ENERGY_EQUIPMENT_SERVICES, Country.IT, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    TRN("TRN.MI", "Terna", Field.ELECTRIC_UTILITIES, Country.IT, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    UCG("UCG.MI", "UniCredit", Field.BANKS, Country.IT, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    US("UNI.MI", "Unipol", Field.INSURANCE, Country.IT, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    BGN("BGN.MI", "Banca Generali", Field.BANKS, Country.IT, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    SOL("SOL.MI", "SOL", Field.CHEMICALS, Country.IT, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    BC("BC.MI", "Brunello Cucinelli", Field.TEXTILES_APPAREL_LUXURY_GOODS, Country.IT, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),


    ANA("ANA.MC", "Acciona", Field.CONSTRUCTION_ENGINEERING, Country.ES, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    ANE("ANE.MC", "Acciona Energía", Field.INDEPENDENT_POWER_PRODUCERS_ENERGY_TRADERS, Country.ES, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    ACS("ACS.MC", "ACS", Field.CONSTRUCTION_ENGINEERING, Country.ES, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    ACX("ACX.MC", "Acerinox", Field.METALS_MINING, Country.ES, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    AENA("AENA.MC", "Aena", Field.TRANSPORTATION_INFRASTRUCTURE, Country.ES, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    AMS("AMS.MC", "Amadeus IT Group", Field.IT_SERVICES, Country.ES, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    MTS("MTS.MC", "ArcelorMittal", Field.METALS_MINING, Country.ES, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    SAB("SAB.MC", "Banco Sabadell", Field.BANKS, Country.ES, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    SANMC("SAN.MC", "Banco Santander", Field.BANKS, Country.ES, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    BKT("BKT.MC", "Bankinter", Field.BANKS, Country.ES, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    BBVA("BBVA.MC", "BBVA", Field.BANKS, Country.ES, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    CABK("CABK.MC", "CaixaBank", Field.BANKS, Country.ES, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    CLNX("CLNX.MC", "Cellnex Telecom", Field.DIVERSIFIED_TELECOMMUNICATION_SERVICES, Country.ES, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    ENG("ENG.MC", "Enagás", Field.GAS_UTILITIES, Country.ES, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    ELE("ELE.MC", "Endesa", Field.ELECTRIC_UTILITIES, Country.ES, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    FER("FER.MC", "Ferrovial", Field.TRANSPORTATION_INFRASTRUCTURE, Country.ES, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    FDR("FDR.MC", "Fluidra", Field.BUILDING_PRODUCTS, Country.ES, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    GRF("GRF.MC", "Grifols", Field.BIOTECHNOLOGY, Country.ES, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    IAG("IAG.MC", "International Consolidated Airlines Group", Field.AIRLINES, Country.ES, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    IBE("IBE.MC", "Iberdrola", Field.ELECTRIC_UTILITIES, Country.ES, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    ITX("ITX.MC", "Inditex", Field.TEXTILES_APPAREL_LUXURY_GOODS, Country.ES, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    IDR("IDR.MC", "Indra Sistemas", Field.AEROSPACE_DEFENSE, Country.ES, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    COL("COL.MC", "Inmobiliaria Colonial", Field.EQUITY_REAL_ESTATE_INVESTMENT_TRUSTS, Country.ES, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    LOG("LOG.MC", "Logista", Field.AIR_FREIGHT_LOGISTICS, Country.ES, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    MAP("MAP.MC", "Mapfre", Field.INSURANCE, Country.ES, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    MRL("MRL.MC", "Merlin Properties", Field.EQUITY_REAL_ESTATE_INVESTMENT_TRUSTS, Country.ES, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    NTGY("NTGY.MC", "Naturgy", Field.MULTI_UTILITIES, Country.ES, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    RED("RED.MC", "Redeia", Field.ELECTRIC_UTILITIES, Country.ES, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    REP("REP.MC", "Repsol", Field.OIL_GAS_CONSUMABLE_FUELS, Country.ES, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    ROVI("ROVI.MC", "Laboratorios Rovi", Field.PHARMACEUTICALS, Country.ES, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    SCYR("SCYR.MC", "Sacyr", Field.CONSTRUCTION_ENGINEERING, Country.ES, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    TEF("TEF.MC", "Telefónica", Field.DIVERSIFIED_TELECOMMUNICATION_SERVICES, Country.ES, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    UNI("UNI.MC", "Unicaja Banco", Field.BANKS, Country.ES, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    SLER("SLR.MC", "Solaria Energía y Medio Ambiente", Field.INDEPENDENT_POWER_PRODUCERS_ENERGY_TRADERS, Country.ES, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),

    ACKB("ACKB.BR", "Ackermans & van Haaren", Field.DIVERSIFIED_FINANCIAL_SERVICES, Country.BE, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    ARGX("ARGX.BR", "argenx", Field.BIOTECHNOLOGY, Country.BE, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    ABI("ABI.BR", "Anheuser-Busch InBev", Field.BEVERAGES, Country.BE, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    AZB("AZE.BR", "Azelis Group", Field.CHEMICALS, Country.BE, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    BEKB("BEKB.BR", "Bekaert", Field.METALS_MINING, Country.BE, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    DIE("DIE.BR", "D'Ieteren Group", Field.DISTRIBUTORS, Country.BE, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    ELI("ELI.BR", "Elia Group", Field.ELECTRIC_UTILITIES, Country.BE, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    GBLB("GBLB.BR", "Groupe Bruxelles Lambert", Field.DIVERSIFIED_FINANCIAL_SERVICES, Country.BE, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    KBC("KBC.BR", "KBC Group", Field.BANKS, Country.BE, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    LOTB("LOTB.BR", "Lotus Bakeries", Field.FOOD_PRODUCTS, Country.BE, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    MELE("MELE.BR", "Melexis", Field.SEMICONDUCTORS, Country.BE, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    PRX("PROX.BR", "Proximus", Field.DIVERSIFIED_TELECOMMUNICATION_SERVICES, Country.BE, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    SOF("SOF.BR", "Sofina", Field.CAPITAL_MARKETS, Country.BE, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    SOLBBR("SOLB.BR", "Solvay", Field.CHEMICALS, Country.BE, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    SYENS("SYENS.BR", "Syensqo", Field.CHEMICALS, Country.BE, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    UCB("UCB.BR", "UCB", Field.PHARMACEUTICALS, Country.BE, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    UMI("UMI.BR", "Umicore", Field.CHEMICALS, Country.BE, Currency.EUR, ZoneIdEnum.EUROPE_PARIS),
    WDP("WDP.BR", "Warehouses De Pauw", Field.EQUITY_REAL_ESTATE_INVESTMENT_TRUSTS, Country.BE, Currency.EUR, ZoneIdEnum.EUROPE_PARIS);

    private final String ticker;
    private final String label;
    private final Field field;
    private final Country country;
    private final Currency currency;
    private final ZoneIdEnum zoneIdEnum;


    Stock(String ticker, String label, Field field, Country country, Currency currency, ZoneIdEnum zoneIdEnum) {
        this.ticker = ticker;
        this.country = country;
        this.field = field;
        this.label = label;
        this.currency = currency;
        this.zoneIdEnum = zoneIdEnum;
    }
}
